Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          UpAssist.Neos.Reactions:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        UpAssist.Neos.Reactions: true
  Flow:
    mvc:
      routes:
        UpAssist.Neos.Reactions: true
